# Generated by Django 5.2.7 on 2025-10-17 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='correo electrónico')),
                ('full_name', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('phone', models.CharField(max_length=20, verbose_name='teléfono')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verificado')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado el')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drawn_at', models.DateTimeField(auto_now_add=True, verbose_name='sorteado el')),
                ('notified', models.BooleanField(default=False, verbose_name='notificado')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='notificado el')),
                ('prize_description', models.TextField(default='Estadía de 2 noches todo pagado para pareja en hotel', verbose_name='descripción del premio')),
                ('drawn_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draws_made', to=settings.AUTH_USER_MODEL, verbose_name='sorteado por')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL, verbose_name='participante ganador')),
            ],
            options={
                'verbose_name': 'ganador',
                'verbose_name_plural': 'ganadores',
                'ordering': ['-drawn_at'],
            },
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['email'], name='participant_email_3b27de_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_verified'], name='participant_is_veri_dd1d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['created_at'], name='participant_created_f2bfe0_idx'),
        ),
    ]
