databases:
  - name: sorteo-db
    databaseName: sorteo_san_valentin
    user: sorteo_user
    plan: free

services:
  # Backend Django
  - type: web
    name: sorteo-backend
    runtime: python
    region: oregon
    plan: free
    branch: master
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: sorteo-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: FRONTEND_URL
        value: "https://sorteo-san-valentin-frontend.vercel.app"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@ctsturismo.cl"
